- name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # O conteúdo desta pasta vai para a raiz da branch
          branch: stable-website
          clean: true
